### ISSUE TITLE
Issues in running obelisc

### ISSUE THREAD

**Issue by ghost** [qsonehara/Obelisc#1]
Dear @qsonehara,

I receive errors while running obelisc command with both the example sets and a personal sets, made by Plink 1.9
I report below the errors:

```
 obelisc hapmap3_r2_b37_fwd.consensus.qc.poly.JPT.example -c hapmap3_r2_b37_fwd.consensus.qc.poly.JPT.example.case -w 1500 -s 1500 -o example_ibdmapping -f example_out.pdf
/home/path/example
SNP data loaded.
Traceback (most recent call last):
  File "/home/.local/bin/obelisc", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.8/site-packages/obelisc/main.py", line 375, in main
    mapping = Mapping(args.prefix, args.case_file)
  File "/home/.local/lib/python3.8/site-packages/obelisc/main.py", line 59, in __init__
    L.append(i[1].decode('utf-8'))
AttributeError: 'numpy.str_' object has no attribute 'decode'
```
Is there any known solution?

**Comment by qsonehara** [comment]
Hi Mirko,

Would you mind providing the version of the pysnptools module installed in your python environment?

**Comment by ghost** [comment]
Hi Kyuto,

thank you for your reply.
My version of pysnptools is 0.5.2

**Comment by qsonehara** [comment]
Thanks for the information.
I have reproduced the error, after updating pysnptools in my environment from version 0.3.14 to 0.5.2.
It seems like that several data type handling in pysnptools has been changed.
I will fix the obelisc code to resolve the data type inconsistency with the latest version of the module.

**Comment by ghost** [comment]
Hi! 
Thank you for the update. Let's be in touch for this resolution!

**Comment by qsonehara** [comment]
I have updated the data-load part of obelisc. The new code seems to run with the latest pysnptools in my environment.
Please give it a try!

**Comment by ghost** [comment]
Hi @qsonehara!
Finally, it works!

I've tried both the example file (provided in the GitHub repository) and a personal dataset (made of WES file merged with the 1000 Genomes Projects), for a total of over 2500 samples and almost 100.000 SNPs.

I'll close this issue, thank you so much!
